### ISSUE TITLE
.gitignore file

### ISSUE THREAD

**Issue by mariothedog** [kizule/hacktoberfest-2021#70]
My main concern is this [pycache file](https://github.com/kizule/hacktoberfest-2021/tree/main/Python/Blackjack%20Game/__pycache__) committed.
Perhaps we can use [this](https://github.com/github/gitignore/blob/master/Python.gitignore) for now?

**Comment by kizule** [comment]
Makes sense, thank you @mariothedog! I will take a look at your pull request.
